#!/bin/zsh
# Weekly Memory Summary + Security Audit for OpenClaw HQ
# Runs every Sunday at 9:00 AM
# Location: ~/.openclaw/scripts/weekly-summary.sh

set -e

# Run security audit first
echo "Running security audit..."
~/.openclaw/scripts/security-audit.sh || true

# Configuration
MEMORY_DIR="$HOME/.openclaw/memory"
REPO_DIR="$HOME/.openclaw/OpenClaw-HQ"
TELEGRAM_BOT_TOKEN="7830016303:AAHokRCjzvhwb5kM96yYQXqXf-ZcrqWswnw"
TELEGRAM_CHAT_ID="6026695075"
WEEK_NUMBER=$(date +%U)
YEAR=$(date +%Y)
DATE=$(date +%Y-%m-%d)

# Colors for terminal output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "${GREEN}Generating weekly summary for Week ${WEEK_NUMBER}...${NC}"

# Create weekly summary file
SUMMARY_FILE="${MEMORY_DIR}/_WEEK-${WEEK_NUMBER}.md"
ARCHIVE_DIR="${MEMORY_DIR}/archive/${YEAR}"

mkdir -p "$ARCHIVE_DIR"

# Collect daily logs from this week (Sunday to Saturday)
WEEK_START=$(date -v-sun +%Y-%m-%d 2>/dev/null || date -d "last sunday" +%Y-%m-%d)
WEEK_END=$(date -v-sat +%Y-%m-%d 2>/dev/null || date -d "next saturday" +%Y-%m-%d)

echo "Week range: ${WEEK_START} to ${WEEK_END}"

# Generate summary content
cat > "$SUMMARY_FILE" << EOF
# Week ${WEEK_NUMBER} Summary (${WEEK_START} to ${WEEK_END})

**Generated:** ${DATE}  
**By:** Brain Agent (Rick)  
**Location:** Mac mini

---

## 📊 Overview

### Sessions This Week
$(ls -1 ${MEMORY_DIR}/2026-*.md 2>/dev/null | wc -l | xargs echo "Daily logs:")

### Focus Areas
$(grep -h "## Session Overview" ${MEMORY_DIR}/2026-*.md 2>/dev/null | head -5)

---

## ✅ Completed This Week

$(grep -h "### ✅ Completed" ${MEMORY_DIR}/2026-*.md 2>/dev/null | sed 's/### ✅ Completed/\n---\n/' | tail -20)

---

## 🔄 In Progress

$(grep -h "### 🔄 In Progress" ${MEMORY_DIR}/2026-*.md 2>/dev/null | sed 's/### 🔄 In Progress/\n/' | tail -10)

---

## ⏸️ Blockers/Deferred

$(grep -h "### ⏸️ Blocked" ${MEMORY_DIR}/2026-*.md 2>/dev/null | sed 's/### ⏸️ Blocked/\n/' | tail -10)

---

## 💰 Cost Tracking

**Target:** $60-80/month  
**Status:** [To be updated with actual metrics]

---

## 🔜 Next Week Priorities

$(grep -h "## Next Session Priorities" ${MEMORY_DIR}/2026-*.md 2>/dev/null | head -1)
$(grep -A5 "## Next Session Priorities" ${MEMORY_DIR}/2026-*.md 2>/dev/null | grep "\- \[" | tail -5)

---

## 📁 Full Logs

All daily logs available at:  
https://github.com/mortylobster-droid/OpenClaw-HQ/tree/main/memory

---

*This summary was automatically generated by the Brain Agent.*
EOF

echo "${GREEN}Summary created: ${SUMMARY_FILE}${NC}"

# Create Telegram message (shorter version)
TELEGRAM_MSG=$(cat << EOF
📊 *OpenClaw HQ - Week ${WEEK_NUMBER} Summary*

🗓 ${WEEK_START} to ${WEEK_END}

$(grep -h "### ✅ Completed" ${MEMORY_DIR}/2026-*.md 2>/dev/null | wc -l | xargs echo "✅ Completed items:")
$(grep -h "### 🔄 In Progress" ${MEMORY_DIR}/2026-*.md 2>/dev/null | wc -l | xargs echo "🔄 In progress:")

📈 *Focus Areas:*
$(grep -h "Focus:" ${MEMORY_DIR}/2026-*.md 2>/dev/null | sed 's/Focus:/\n•/' | tail -3)

💰 *Cost Status:*
Target: $60-80/month
[Check dashboards for actual spend]

📁 *Full logs:*
https://github.com/mortylobster-droid/OpenClaw-HQ/tree/main/memory

🤖 _Generated by Rick (Brain Agent)_
EOF
)

# Send to Telegram
echo "${YELLOW}Sending to Telegram...${NC}"

curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
  -H "Content-Type: application/json" \
  -d "{
    \"chat_id\": \"${TELEGRAM_CHAT_ID}\",
    \"text\": \"$(echo "$TELEGRAM_MSG" | sed 's/"/\\"/g')\",
    \"parse_mode\": \"Markdown\",
    \"disable_web_page_preview\": true
  }" > /dev/null

echo "${GREEN}✅ Telegram message sent!${NC}"

# Archive old daily logs (>30 days)
echo "${YELLOW}Archiving old logs...${NC}"
find "$MEMORY_DIR" -name "2026-*.md" -mtime +30 -exec mv {} "$ARCHIVE_DIR/" \; 2>/dev/null || true

# Push to GitHub
echo "${YELLOW}Pushing to GitHub...${NC}"
cd "$REPO_DIR"
git add memory/
git commit -m "memory: Week ${WEEK_NUMBER} summary

Auto-generated weekly summary including:
- Completed items
- In-progress work
- Blockers and deferred tasks
- Cost tracking status

Daily logs archived after 30 days." || echo "No changes to commit"
git push origin main || echo "Push failed or already up to date"

echo "${GREEN}✅ Weekly summary complete!${NC}"
echo "Summary: ${SUMMARY_FILE}"
echo "Archived to: ${ARCHIVE_DIR}"
